
export const ALL_TASKS_REQUEST = "ALL_TASKS_REQUEST";
export const ALL_TASKS_SUCCESS = "ALL_TASKS_SUCCESS";
export const ALL_TASKS_FAIL = "ALL_TASKS_FAIL";

export const ADD_TASK_REQUEST = "ADD_TASK_REQUEST";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAIL = "ADD_TASK_FAIL";

export const TASK_DETAIL_REQUEST = "TASK_DETAIL_REQUEST";
export const TASK_DETAIL_SUCCESS = "TASK_DETAIL_SUCCESS";
export const TASK_DETAIL_FAIL = "TASK_DETAIL_FAIL";


export const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL";

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";

export const ADD_TASK_NOTE_REQUEST = "ADD_TASK_NOTE_REQUEST";
export const ADD_TASK_NOTE_SUCCESS = "ADD_TASK_NOTE_SUCCESS";
export const ADD_TASK_NOTE_FAIL = "ADD_TASK_NOTE_FAIL";

export const GET_TASK_NOTES_REQUEST = "GET_TASK_NOTES_REQUEST";
export const GET_TASK_NOTES_SUCCESS = "GET_TASK_NOTES_SUCCESS";
export const GET_TASK_NOTES_FAIL = "GET_TASK_NOTES_FAIL";

export const DELETE_TASK_NOTE_REQUEST = "DELETE_TASK_NOTE_REQUEST";
export const DELETE_TASK_NOTE_SUCCESS = "DELETE_TASK_NOTE_SUCCESS";
export const DELETE_TASK_NOTE_FAIL = "DELETE_TASK_NOTE_FAIL";

export const GET_STATUS_REQUEST = "GET_STATUS_REQUEST";
export const GET_STATUS_SUCCESS = "GET_STATUS_SUCCESS";
export const GET_STATUS_FAIL = "GET_STATUS_FAIL";


export const USER_TASKS_REQUEST = "USER_TASKS_REQUEST";
export const USER_TASKS_SUCCESS = "USER_TASKS_SUCCESS";
export const USER_TASKS_FAIL = "USER_TASKS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
